ALTER TABLE `config`
  ADD COLUMN IF NOT EXISTS `direccion` varchar(200) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ciudad`    varchar(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `provincia` varchar(100) DEFAULT NULL;
